# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jherzog <jherzog@student.42wolfsburg.de    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/12 17:59:00 by jherzog           #+#    #+#              #
#    Updated: 2023/02/12 18:35:59 by jherzog          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

SOURCE	=	main.c			\
			error_checks.c	\
			translate.c		\
			ft_func.c		\

all:
	cc -Wall -Wextra -Werror $(SOURCE) -o $(NAME)

fclean:
	rm -f $(NAME)